### ISSUE TITLE
question on usage

### ISSUE THREAD

**Issue by begoat** [shettyh/istio-samples#1]
First, Thank you for this repo. I am struggling with grpc on istio. I cannot find enough example.

Then i have a question related to usage:
after expose `app-gateway` listening port 9090, how can i have access to the service; use ingress_gateway_ip:9090? Do i need manually change port exposed by ingress_gateway?

**Comment by shettyh** [comment]
Sorry for less info about the usage, i am yet to find time to add enough details on how to use and what each files means in repo.

To answer your question, you need to expose the gateway port through `ingressgateway` service.

![image](https://user-images.githubusercontent.com/13759916/43684601-c3c9aa84-98c0-11e8-8f7e-7b1058b6ba0f.png)

As you can see in the above picture i am adding a another port mapping in `ingressgateway` service to expose `9090` through `NodePort 31399` . Once you did that then you can access your `gRPC` services through `31999`.

After adding that in `svc` you should be able to see the port exposed through `kubectl get svc -n istio-system` command 

![image](https://user-images.githubusercontent.com/13759916/43684630-42d223b0-98c1-11e8-816d-385183fc919c.png)


Hope that answers your question

**Comment by begoat** [comment]
Thank you for the quick reply and the answer. It worked.
